const Department = require('../Api/Models/Association');
const sequelize = require('../Config/Database/sequelize.config');

const departments = [
  {
    name: 'Main Server',
    head_of_department: 'John Doe',
    branch: 'Main',
    branch_of_department: 'Main',
    contact_number: '1234567890',
    address: '123 Main St, City, Country',
    email: 'main_server@example.com',
    department_code: 'HR001',
    status: 'Active',
    date_founded: new Date('2020-01-01'),
    num_employees: 50,
    description: 'Handles all server management and infrastructure.',
    created_by: 'System',
    updated_by: 'System',
  },
  {
    name: 'Pharmacy',
    head_of_department: 'Jane Smith',
    branch: 'Pharmacy',
    branch_of_department: 'Pharmacy',
    contact_number: '1234567891',
    address: '456 Pharmacy Ave, City, Country',
    email: 'pharmacy@example.com',
    department_code: 'PH001',
    status: 'Active',
    date_founded: new Date('2019-05-15'),
    num_employees: 30,
    description: 'Handles medication and health products.',
    created_by: 'System',
    updated_by: 'System',
  },
  {
    name: 'Logistics',
    head_of_department: 'Alice Brown',
    branch: 'Logistics',
    branch_of_department: 'Logistics',
    contact_number: '1234567892',
    address: '789 Logistics Rd, City, Country',
    email: 'logistics@example.com',
    department_code: 'LOG001',
    status: 'Active',
    date_founded: new Date('2018-07-20'),
    num_employees: 40,
    description: 'Manages all product deliveries and distribution.',
    created_by: 'System',
    updated_by: 'System',
  },
  {
    name: 'Customer Support',
    head_of_department: 'Bob White',
    branch: 'Customer Support',
    branch_of_department: 'Customer Support',
    contact_number: '1234567893',
    address: '101 Support Lane, City, Country',
    email: 'customer_support@example.com',
    department_code: 'CS001',
    status: 'Active',
    date_founded: new Date('2017-03-25'),
    num_employees: 20,
    description: 'Handles customer queries and support tickets.',
    created_by: 'System',
    updated_by: 'System',
  },
  {
    name: 'Sales & Marketing',
    head_of_department: 'Emma Green',
    branch: 'Sales & Marketing',
    branch_of_department: 'Sales & Marketing',
    contact_number: '1234567894',
    address: '202 Sales Ave, City, Country',
    email: 'sales_marketing@example.com',
    department_code: 'SM001',
    status: 'Active',
    date_founded: new Date('2016-09-10'),
    num_employees: 35,
    description: 'Manages all sales and marketing campaigns.',
    created_by: 'System',
    updated_by: 'System',
  },
  {
    name: 'Finance & Accounting',
    head_of_department: 'Liam Black',
    branch: 'Finance & Accounting',
    branch_of_department: 'Finance & Accounting',
    contact_number: '1234567895',
    address: '303 Finance St, City, Country',
    email: 'finance_accounting@example.com',
    department_code: 'FA001',
    status: 'Active',
    date_founded: new Date('2015-11-05'),
    num_employees: 25,
    description: 'Handles financial records and accounting processes.',
    created_by: 'System',
    updated_by: 'System',
  },
  {
    name: 'Compliance & Legal',
    head_of_department: 'Sophia Blue',
    branch: 'Compliance & Legal',
    branch_of_department: 'Compliance & Legal',
    contact_number: '1234567896',
    address: '404 Legal Blvd, City, Country',
    email: 'compliance_legal@example.com',
    department_code: 'CL001',
    status: 'Active',
    date_founded: new Date('2014-12-12'),
    num_employees: 15,
    description: 'Ensures legal compliance and handles contracts.',
    created_by: 'System',
    updated_by: 'System',
  },
  {
    name: 'Healthcare',
    head_of_department: 'Ethan Red',
    branch: 'Healthcare',
    branch_of_department: 'Healthcare',
    contact_number: '1234567897',
    address: '505 Healthcare Ave, City, Country',
    email: 'healthcare@example.com',
    department_code: 'HC001',
    status: 'Active',
    date_founded: new Date('2013-06-10'),
    num_employees: 40,
    description: 'Provides healthcare services and medical management.',
    created_by: 'System',
    updated_by: 'System',
  },
  {
    name: 'IT Development',
    head_of_department: 'Olivia Purple',
    branch: 'IT Development',
    branch_of_department: 'IT Development',
    contact_number: '1234567898',
    address: '606 IT Rd, City, Country',
    email: 'it_development@example.com',
    department_code: 'IT001',
    status: 'Active',
    date_founded: new Date('2012-08-25'),
    num_employees: 60,
    description:
      'Responsible for all IT infrastructure and software development.',
    created_by: 'System',
    updated_by: 'System',
  },
  {
    name: 'Inventory Management',
    head_of_department: 'Noah Yellow',
    branch: 'Inventory Management',
    branch_of_department: 'Inventory Management',
    contact_number: '1234567899',
    address: '707 Inventory Rd, City, Country',
    email: 'inventory_management@example.com',
    department_code: 'IM001',
    status: 'Active',
    date_founded: new Date('2011-05-30'),
    num_employees: 50,
    description: 'Manages inventory control and stock records.',
    created_by: 'System',
    updated_by: 'System',
  },
  {
    name: 'Data Analytics',
    head_of_department: 'Ava Pink',
    branch: 'Data Analytics',
    branch_of_department: 'Data Analytics',
    contact_number: '1234567800',
    address: '808 Data St, City, Country',
    email: 'data_analytics@example.com',
    department_code: 'DA001',
    status: 'Active',
    date_founded: new Date('2010-01-10'),
    num_employees: 25,
    description: 'Handles data analysis and business intelligence.',
    created_by: 'System',
    updated_by: 'System',
  },
  {
    name: 'Human Resources',
    head_of_department: 'William Gray',
    branch: 'HR',
    branch_of_department: 'Human Resources',
    contact_number: '1234567801',
    address: '909 HR Rd, City, Country',
    email: 'hr@example.com',
    department_code: 'HR002',
    status: 'Active',
    date_founded: new Date('2009-11-15'),
    num_employees: 40,
    description: 'Manages employee relations and organizational structure.',
    created_by: 'System',
    updated_by: 'System',
  },
  {
    name: 'Partnerships',
    head_of_department: 'Isabella Violet',
    branch: 'Partnerships',
    branch_of_department: 'Partnerships',
    contact_number: '1234567802',
    address: '1010 Partnerships St, City, Country',
    email: 'partnerships@example.com',
    department_code: 'PA001',
    status: 'Active',
    date_founded: new Date('2008-04-23'),
    num_employees: 10,
    description: 'Handles business partnerships and external relationships.',
    created_by: 'System',
    updated_by: 'System',
  },
];

sequelize.MAIN_DB_NAME.sync({ force: false })
  .then(() => {
    return Department.bulkCreate(departments);
  })
  .then(() => {
    console.log('Departments inserted successfully!');
  })
  .catch((error) => {
    console.error('Error inserting departments:', error);
  });
